/** @type {import('tailwindcss').Config} */
export default  {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{vue,js}",
  ],
  theme: {
    extend: {
      colors: {
        "secondary-fixed-dim": "#4fdbc8",
        "tertiary-container": "#742fe5",
        "secondary-container": "#6df5e1",
        "secondary-fixed": "#71f8e4",
        "on-tertiary-container": "#e2d2ff",
        "surface-tint": "#0056d2",
        "outline": "#737785",
        "on-secondary-container": "#006f64",
        "tertiary": "#5a00c7",
        "on-error-container": "#93000a",
        "background": "#f8f9ff",
        "secondary": "#006b5f",
        "on-tertiary-fixed": "#25005a",
        "inverse-surface": "#213145",
        "primary-fixed": "#dae2ff",
        "tertiary-fixed-dim": "#d2bbff",
        "surface-container-low": "#eff4ff",
        "on-tertiary": "#ffffff",
        "inverse-primary": "#b2c5ff",
        "surface-container": "#e5eeff",
        "on-tertiary-fixed-variant": "#5a00c6",
        "primary-fixed-dim": "#b2c5ff",
        "inverse-on-surface": "#eaf1ff",
        "on-secondary": "#ffffff",
        "on-secondary-fixed-variant": "#005048",
        "surface-bright": "#f8f9ff",
        "on-primary-fixed-variant": "#0040a1",
        "surface-container-highest": "#d3e4fe",
        "on-primary-fixed": "#001847",
        "on-error": "#ffffff",
        "error": "#ba1a1a",
        "on-primary": "#ffffff",
        "surface-container-high": "#dce9ff",
        "error-container": "#ffdad6",
        "surface": "#f8f9ff",
        "surface-container-lowest": "#ffffff",
        "primary-container": "#0056d2",
        "primary": "#0040a1",
        "on-secondary-fixed": "#00201c",
        "surface-variant": "#d3e4fe",
        "surface-dim": "#cbdbf5",
        "on-primary-container": "#ccd8ff",
        "on-surface-variant": "#424654",
        "on-background": "#0b1c30",
        "on-surface": "#0b1c30",
        "outline-variant": "#c3c6d6",
        "tertiary-fixed": "#eaddff",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}